# Generated by Django 6.0.3 on 2026-03-27 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM content_blog_tags; DELETE FROM content_blog;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('name', models.CharField(max_length=100, verbose_name='Kategoriya nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Blog kategoriyasi',
                'verbose_name_plural': 'Blog kategoriyalari',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='school.teacher', verbose_name='Muallif'),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='content.blogcategory', verbose_name='Kategoriya'),
        ),
    ]
