# Generated by Django 6.0.3 on 2026-03-24 12:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Blog matni'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Blog matni'),
        ),
        migrations.AddField(
            model_name='blog',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Blog matni'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='gallerycategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uz',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maqola matni'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Kategoriya nomi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Tag nomi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Tag nomi'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Tag nomi'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to='news/extra/', verbose_name='Rasm'),
        ),
    ]
