# Generated by Django 6.0.3 on 2026-03-31 06:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_blogcategory_alter_blog_author_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('question_uz', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_ru', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('question_en', models.CharField(max_length=500, null=True, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('answer_uz', models.TextField(null=True, verbose_name='Javob')),
                ('answer_ru', models.TextField(null=True, verbose_name='Javob')),
                ('answer_en', models.TextField(null=True, verbose_name='Javob')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Ko'p so'raladigan savol",
                'verbose_name_plural': "Ko'p so'raladigan savollar",
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(help_text="Tavsiya etilgan o'lcham: 1200×630 px. Nisbat: 16:9. Fayl: JPG yoki PNG, max 2 MB.", upload_to='blog/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(help_text="Tavsiya etilgan o'lcham: 1200×800 px. Nisbat: 3:2. Fayl: JPG yoki PNG, max 3 MB.", upload_to='gallery/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(help_text="Tavsiya etilgan o'lcham: 1200×630 px. Nisbat: 16:9 (OG image). Fayl: JPG yoki PNG, max 2 MB.", upload_to='news/main/', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(help_text="Tavsiya etilgan o'lcham: 1200×800 px. Nisbat: 3:2. Fayl: JPG yoki PNG, max 2 MB.", upload_to='news/extra/', verbose_name='Rasm'),
        ),
    ]
