# Generated by Django 6.0.3 on 2026-04-01 06:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_add_faq_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Sarlavha')),
                ('youtube_link', models.URLField(help_text='YouTube Shorts yoki oddiy video havolasi', verbose_name='YouTube havola')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Maktab lavhasi',
                'verbose_name_plural': 'Maktab lavhalari',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
