# Generated by Django 6.0.3 on 2026-03-24 12:32

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Maktab haqida matn')),
                ('content_uz', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maktab haqida matn')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maktab haqida matn')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Maktab haqida matn')),
                ('photo1', models.ImageField(upload_to='school/about/', verbose_name='Rasm 1')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='school/about/', verbose_name='Rasm 2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='school/about/', verbose_name='Rasm 3')),
            ],
            options={
                'verbose_name': 'Maktab haqida',
                'verbose_name_plural': 'Maktab haqida',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('full_name', models.CharField(max_length=255, verbose_name='Foydalanuvchi ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
            },
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('name', models.CharField(max_length=100, verbose_name='Fan nomi')),
                ('name_uz', models.CharField(max_length=100, null=True, verbose_name='Fan nomi')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Fan nomi')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Fan nomi')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('label', models.CharField(help_text="Masalan: O'quvchilar soni", max_length=100, verbose_name='Nomi')),
                ('label_uz', models.CharField(help_text="Masalan: O'quvchilar soni", max_length=100, null=True, verbose_name='Nomi')),
                ('label_ru', models.CharField(help_text="Masalan: O'quvchilar soni", max_length=100, null=True, verbose_name='Nomi')),
                ('label_en', models.CharField(help_text="Masalan: O'quvchilar soni", max_length=100, null=True, verbose_name='Nomi')),
                ('value', models.PositiveIntegerField(verbose_name='Qiymati (Soni)')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('full_name', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('full_name_uz', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name="To'liq ism")),
                ('image', models.ImageField(upload_to='school/teachers/', verbose_name='Rasm')),
                ('experience', models.CharField(max_length=100, verbose_name='Tajriba')),
                ('experience_uz', models.CharField(max_length=100, null=True, verbose_name='Tajriba')),
                ('experience_ru', models.CharField(max_length=100, null=True, verbose_name='Tajriba')),
                ('experience_en', models.CharField(max_length=100, null=True, verbose_name='Tajriba')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('about', django_ckeditor_5.fields.CKEditor5Field(verbose_name="O'qituvchi haqida")),
                ('about_uz', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name="O'qituvchi haqida")),
                ('about_ru', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name="O'qituvchi haqida")),
                ('about_en', django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name="O'qituvchi haqida")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='Lavozimi')),
                ('position_uz', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lavozimi')),
                ('position_ru', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lavozimi')),
                ('position_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Lavozimi')),
                ('sciences', models.ManyToManyField(blank=True, null=True, related_name='teachers', to='school.science', verbose_name='Dars beradigan fanlari')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('weekday', models.CharField(choices=[('mon', 'Dushanba'), ('tue', 'Seshanba'), ('wed', 'Chorshanba'), ('thu', 'Payshanba'), ('fri', 'Juma'), ('sat', 'Shanba'), ('sun', 'Yakshanba')], max_length=3, verbose_name='Hafta kuni')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.science', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='school.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars jadvali',
                'verbose_name_plural': 'Dars jadvallari',
            },
        ),
        migrations.CreateModel(
            name='LessonExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Mavzu nomi')),
                ('youtube_link', models.URLField(verbose_name='YouTube havola')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='school.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Dars namunasi',
                'verbose_name_plural': 'Dars namunalari',
            },
        ),
    ]
