# Generated by Django 6.0.3 on 2026-05-13 06:23

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('full_name', models.CharField(max_length=128, verbose_name="To'liq ism")),
                ('photo', models.ImageField(upload_to='school/founder/', verbose_name='Rasm')),
                ('about_founder', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Asoschi haqida')),
                ('work_status', models.CharField(help_text="Masalan: 'Elite' zavodi asoschisi va direktori", max_length=255, verbose_name='Asosiy faoliyati va lavozimi')),
                ('founder_message', django_ckeditor_5.fields.CKEditor5Field(help_text="Nima uchun aynan ushbu maktabga asos solingani haqida qisqa so'z", verbose_name='Asoschi murojaati')),
            ],
            options={
                'verbose_name': 'Maktab asoschisi',
                'verbose_name_plural': 'Maktab asoschisi',
            },
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Ish vaqti', 'verbose_name_plural': 'Ish vaqtlari'},
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo3',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(help_text="Tavsiya etilgan o'lcham: 600×800 px. Nisbat: 3:4 (portret). Fayl: JPG yoki PNG, max 2 MB.", upload_to='school/teachers/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='about',
            name='founder',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='founder', to='school.founder', verbose_name='Founder'),
        ),
    ]
