# Generated by Django 6.0.3 on 2026-03-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='science',
        ),
    ]
