# Generated by Django 6.0.3 on 2026-03-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_schedule_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name_ru',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='full_name_uz',
        ),
    ]
