# Generated by Django 6.0.3 on 2026-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_teacher_full_name_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['order'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Xodimlar'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('management', 'Rahbariyat'), ('teacher', "O'qituvchi")], default='teacher', max_length=20, verbose_name='Xodim turi'),
        ),
    ]
