# Generated by Django 6.0.3 on 2026-04-02 06:10

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='yangilangan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktivmi')),
                ('name', models.CharField(default='ELITA AKADEMIK MAKTABI', max_length=50, verbose_name='Maktab nomi')),
                ('slogan', models.CharField(default="Ilmdan o'zga najot yo'q", max_length=50, verbose_name='Maktab nomi')),
                ('logo', models.ImageField(upload_to='core/site-settings/logo', verbose_name='Logo')),
                ('instagram', models.URLField(blank=True, null=True)),
                ('telegram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('main_phone', models.CharField(max_length=20, verbose_name='Asosiy telefon')),
                ('other_phone', models.CharField(max_length=20, verbose_name="Qo'shimcha telefon")),
                ('hero_video', models.FileField(upload_to='core/site-settings/files', validators=[core.validators.validate_video_size], verbose_name='Video')),
                ('reception', models.CharField(default='Dushanba-Juma: 8:30 - 16:30', max_length=50)),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
