# Generated by Django 6.0.3 on 2026-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name_en',
            field=models.CharField(default='ELITA AKADEMIK MAKTABI', max_length=50, null=True, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='name_ru',
            field=models.CharField(default='ELITA AKADEMIK MAKTABI', max_length=50, null=True, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='reception_en',
            field=models.CharField(default='Dushanba-Juma: 8:30 - 16:30', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='reception_ru',
            field=models.CharField(default='Dushanba-Juma: 8:30 - 16:30', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='reception_uz',
            field=models.CharField(default='Dushanba-Juma: 8:30 - 16:30', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_en',
            field=models.CharField(default="Ilmdan o'zga najot yo'q", max_length=50, null=True, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_ru',
            field=models.CharField(default="Ilmdan o'zga najot yo'q", max_length=50, null=True, verbose_name='Maktab nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan_uz',
            field=models.CharField(default="Ilmdan o'zga najot yo'q", max_length=50, null=True, verbose_name='Maktab nomi'),
        ),
    ]
